// apps/web-preact/src/components/UserForm.tsx
import { useSignal } from '@preact/signals';
import { useEffect } from 'preact/hooks';
import {
  createUser,
  fetchUsers,
  loading,
  selectedUser,
  showCreateForm,
  stopEditing,
  updateUser,
} from '../hooks/useJsonRpc';
import type { UserResource } from '../generated';

function getButtonText(isLoading: boolean, isEditing: boolean): string {
  if (isLoading) {
    return isEditing ? 'Saving...' : 'Creating...';
  }
  return isEditing ? 'Save' : 'Create';
}

interface CreateModeProps {
  readonly mode: 'create';
}

interface EditModeProps {
  readonly mode: 'edit';
  readonly user: UserResource;
}

type UserFormProps = CreateModeProps | EditModeProps;

export function UserForm(props: UserFormProps) {
  const user = props.mode === 'edit' ? props.user : null;
  const name = useSignal(user ? user.attributes.name : '');
  const email = useSignal(user ? user.attributes.email : '');
  const formError = useSignal<string | null>(null);

  // Update form when user prop changes
  useEffect(() => {
    name.value = user ? user.attributes.name : '';
    email.value = user ? user.attributes.email : '';
    formError.value = null;
  }, [user?.id]);

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    if (!name.value.trim() || !email.value.trim()) return;

    formError.value = null;

    if (user) {
      // Update existing user
      const result = await updateUser(user.id, name.value.trim(), email.value.trim());

      if (result) {
        name.value = '';
        email.value = '';
        stopEditing();
        selectedUser.value = null;
        void fetchUsers();
      }
    } else {
      // Create new user
      const result = await createUser(name.value.trim(), email.value.trim());

      if (result) {
        name.value = '';
        email.value = '';
        showCreateForm.value = false;
      }
    }
  };

  return (
    <div class="user-card">
      <h3>{user ? 'Edit User' : 'Create User'}</h3>
      {formError.value && <div class="error">{formError.value}</div>}
      <form onSubmit={(e) => void handleSubmit(e)} class="create-form">
        <input
          type="text"
          placeholder="Name"
          value={name.value}
          onInput={(e) => (name.value = (e.target as HTMLInputElement).value)}
        />
        <input
          type="email"
          placeholder="Email"
          value={email.value}
          onInput={(e) => (email.value = (e.target as HTMLInputElement).value)}
        />
        <button type="submit" class="primary" disabled={loading.value}>
          {getButtonText(loading.value, !!user)}
        </button>
      </form>
    </div>
  );
}

// apps/web-angular/src/app/pages/users/components/user-form.component.ts
import { ChangeDetectionStrategy, Component, effect, inject, input, output, signal } from '@angular/core';
import { SignalInputDirective } from '~/app/shared/signal-input.directive';
import { UserResource, UsersFacade } from '~/generated';

@Component({
  selector: 'app-user-form',
  imports: [SignalInputDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="user-card">
      <h3>{{ user() ? 'Edit User' : 'Create User' }}</h3>
      @if (error()) {
        <div class="error">{{ error() }}</div>
      }
      <form (submit)="handleSubmit($event)" class="create-form">
        <input type="text" placeholder="Name" [signal]="name" required />
        <input type="email" placeholder="Email" [signal]="email" required />
        <button type="submit" class="primary" [disabled]="loading()">
          {{ loading() ? (user() ? 'Saving...' : 'Creating...') : user() ? 'Save' : 'Create' }}
        </button>
      </form>
    </div>
  `,
})
export class UserFormComponent {
  private readonly usersFacade = inject(UsersFacade);

  user = input<UserResource>();

  created = output<void>();

  name = signal('');

  email = signal('');

  loading = signal(false);

  error = signal<string | null>(null);

  constructor() {
    effect(() => {
      const u = this.user();
      if (u) {
        this.name.set(u.attributes.name);
        this.email.set(u.attributes.email);
      }
    });
  }

  handleSubmit(event: Event) {
    event.preventDefault();
    const nameVal = this.name().trim();
    const emailVal = this.email().trim();
    if (!nameVal || !emailVal) return;

    this.loading.set(true);
    this.error.set(null);

    const u = this.user();
    const request$ = u
      ? this.usersFacade.updateUser({ id: u.id, name: nameVal, email: emailVal })
      : this.usersFacade.createUser({ name: nameVal, email: emailVal });

    request$.subscribe({
      next: () => {
        this.name.set('');
        this.email.set('');
        this.loading.set(false);
        this.created.emit();
      },
      error: (e: Error) => {
        this.error.set(e.message);
        this.loading.set(false);
      },
    });
  }
}
